# ·▄▄▄▄• ▄▄▄·  ▐ ▄  ▄▄ • ▄▄▄ .▄▄▌  ▄▄▄▄▄ ▄▄▄·  ▄▄ • .▄▄ ·
# ▪▀·.█▌▐█ ▀█ •█▌▐█▐█ ▀ ▪▀▄.▀·██•  •██  ▐█ ▀█ ▐█ ▀ ▪▐█ ▀.
# ▄█▀▀▀•▄█▀▀█ ▐█▐▐▌▄█ ▀█▄▐▀▀▪▄██▪   ▐█.▪▄█▀▀█ ▄█ ▀█▄▄▀▀▀█▄
# █▌▪▄█▀▐█ ▪▐▌██▐█▌▐█▄▪▐█▐█▄▄▌▐█▌▐▌ ▐█▌·▐█ ▪▐▌▐█▄▪▐█▐█▄▪▐█
# ·▀▀▀ • ▀  ▀ ▀▀ █▪·▀▀▀▀  ▀▀▀ .▀▀▀  ▀▀▀  ▀  ▀ ·▀▀▀▀  ▀▀▀▀
#
# This file is part of zAngelTags (Bukkit).
#
# zAngelTags is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Remember to join my Discord server if you need help:
# https://discord.nookure.com/
#
# General configuration for the plugin.
#
Config:
  # The language file you want to use for the plugin messages.
  # Included locales: en.yml (english) and es.yml (spanish)
  language: "en.yml"
  # Enable or disable the debug mode.
  # If enabled, the plugin will send more information about the plugin status.
  debug: false
Database:
  # The type of database you want to use, you can choose between SQLite or MySQL.
  # The MySQL driver also works with MariaDB
  type: 'SQLite'
  # Your database host IP address.
  host: '127.0.0.1'
  # Your database host connection port. Default for MariaDB and MySQL is 3306.
  port: 3306
  # Name of your database. A database server can contain multiple databases.
  database: 'zangeltags'
  # Your database host username.
  user: 'zat'
  # Your database host password.
  password: 'nookure'